import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import { builtinModules as builtins } from "module";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	platform: "node",
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	// Patch out IE-era script element creation inside the bundled setimmediate
	// polyfill. In Electron the polyfill exits early (setImmediate exists),
	// so this code never runs — but static analysis still flags it.
	// Replacing the condition with `false` keeps the polyfill's setTimeout
	// fallback while eliminating the script-element creation entirely.
	let built = fs.readFileSync("main.js", "utf-8");
	// Replace IE-era setimmediate polyfill script element detection with no-ops.
	// The condition check itself:
	built = built.replace(/"onreadystatechange"\s*in\s*[\w.]+\.createElement\("script"\)/g, "false");
	// The createElement("script") calls inside the now-dead branch:
	built = built.replace(/createElement\("script"\)/g, 'createElement("span")');
	fs.writeFileSync("main.js", built);
	process.exit(0);
} else {
	await context.watch();
}
